In [ ]:
!pip install faker

import sqlite3
from faker import Faker

# Setup
conn = sqlite3.connect("dummy_data.db")
cursor = conn.cursor()
fake = Faker()

# Create table
cursor.execute("""
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT,
    address TEXT,
    phone TEXT,
    email TEXT
)
""")

# Insert 200 dummy records
for _ in range(200):
    cursor.execute("""
    INSERT INTO users (name, address, phone, email)
    VALUES (?, ?, ?, ?)
    """, (fake.name(), fake.address(), fake.phone_number(), fake.email()))

# Save & close
conn.commit()
conn.close()

Requirement already satisfied: faker in /usr/local/lib/python3.11/dist-packages (37.1.0)
Requirement already satisfied: tzdata in /usr/local/lib/python3.11/dist-packages (from faker) (2025.2)

In [ ]:
import sqlite3
import pandas as pd

# Connect to the DB
conn = sqlite3.connect("dummy_data.db")

# Read the table into a DataFrame
df = pd.read_sql_query("SELECT * FROM users", conn)

# Display the DataFrame
df.head(200)  # Shows all 200 records

,id,name,address,phone,email
0,1,Melissa Perry,"802 Jennifer Parks\nMarkfort, IA 40019",389.487.0055x908,chase83@example.org
1,2,William Delacruz,"702 Brown Knoll\nDiazburgh, NV 23884",001-844-311-2736x40156,daniel13@example.net
2,3,Kristina Brown,"56943 Kathryn Wall Suite 191\nWest Manuel, GA ...",+1-525-225-5722x10701,andreajackson@example.net
3,4,Adam Bradshaw,"322 Ann Burgs\nSouth Abigail, HI 67519",+1-716-284-2593x3148,laradylan@example.com
4,5,Mark Salinas,"0195 Kaufman Lakes\nBrandonport, KS 81077",970-936-4042x21593,epayne@example.net
...,...,...,...,...,...
195,196,Beth Stewart,"1703 Pamela Glens Apt. 791\nJamesville, CA 20937",(382)429-5782,riveranicholas@example.org
196,197,Andrea Smith,"4888 Allen Station\nNew Wesley, DC 18881",902.731.0186x778,stephaniewilliams@example.org
197,198,Lindsay Rodriguez,"1959 Johnson Court\nAllenmouth, AL 48498",+1-453-977-1386x452,courtneyferrell@example.org
198,199,Ronald Hill,"260 Nicolas Drive\nPughborough, IL 16472",001-576-364-4060x58014,patrickmartin@example.org
199,200,Jennifer Phillips,"560 Rodriguez Station Apt. 659\nSouth Barbara,...",001-579-571-4054x7414,murraymariah@example.com